### PR TITLE
Skip test cases without cls attribute

### LINKED ISSUE #1: pytest collects abstract test cases
I want to use an intermediate abstract test case, which groups some common functionality. Using `pytest` via

```console
pytest tests/
```

these intermediate classes get recognized as tests (since they subclass `unittest.TestCase`), and thus executed leading to a test failure

```python-traceback
AttributeError: '_CommonTests' object has no attribute 'cls'
```

since the abstract classes do not have a class to test.

I see two solutions:
1. Make `GenericTestCase` not subclass from `unittest.TestCase`. This makes it necessary to add `unittest.TestCase` to each "leaf" test case, but allows arbitrary abstract intermediate layers in between which do not get executed themselves.
2. Extend `GenericTestCase` to check for presence of the `cls` attribute, and skip if not present, e.g.
 ```python
T = TypeVar("T")
class GenericTestCase(unittest_templates.GenericTestCase, Generic[T]):
    def setUp(self) -> None:
        if not hasattr(self, "cls"):
            raise SkipTest(f"No cls in {self.__class__}")
        super().setUp()
```
  This still detects the test cases, but skips each abstract one.

### PR DESCRIPTION
**Pull request by mberr**
Fixes #1

### CODE REVIEW

**Comment by cthoyt** [comment]
I updated it with more information on how to fix it

**Comment by cthoyt** [comment]
I'm going to try and add a test

**Comment by cthoyt** [comment]
Wait I have no idea how to test this

**Review by cthoyt — APPROVED** [review]
@mberr if you have any idea how to test that does what it's supposed to, then great. Otherwise, merge it

**Comment by mberr** [comment]
> @mberr if you have any idea how to test that does what it's supposed to, then great. Otherwise, merge it

Not really :sweat_smile: 

The "simplest" solution I can think of is to create an abstract test and a concrete one, run `pytest tests` on them and check whether the output is ok.

**Pull request merged**
